#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
~/.config/polybar/launch.sh &
nm-applet &
killall -q pasystray
pasystray &

feh --bg-fill --randomize ~/Data/Wallpapers/* &
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d         # IX X

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Spotify desktop='^5'
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
